name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14, 12, 10, 8, 6]
    steps:
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
    - if: matrix.node-version == 14
      name: Generate coverage file
      run: npm run test:ci > coverage.lcov
    - if: matrix.node-version == 14
      name: Send coverage info to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.lcov
